-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM FIRST_HALF as FH
INNER JOIN ICECREAM_INFO as II
ON FH.FLAVOR = II.FLAVOR
where FH.TOTAL_ORDER > 3000 and II.INGREDIENT_TYPE = 'fruit_based'
order by FH.TOTAL_ORDER DESC;